services:
  mysql:
    image: mysql:8.0
    container_name: minihub-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: minihub
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: minihub-redis
    ports:
      - "6379:6379"

volumes:
  mysql-data: